In [1]:
import numpy
import torch

In [3]:
x = torch.tensor(2.0,requires_grad= True)
#"x" with a value of 2.0 and tells the program to remember the steps taken on this variable so it can figure out how those steps affect "x" during a process called backpropagation,

In [4]:
y = x**2 + 4*x + 4 # a function y with the variable x

In [5]:
print(y) # when we write 2 in place of x

tensor(16., grad_fn=<AddBackward0>)


In [6]:
y.backward() # runs backpropagation

###### Backward propagation is used  for adjusting the weights of a neural network by propagating the error backward from the output layer to the input layer

In [7]:
x.grad # the derivative of y where x = 2

tensor(8.)

In [10]:
x_new = torch.tensor([[1.,2.],[3.,4.]],requires_grad = True)
print(x_new)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)


#### First Layer

In [12]:
y = x_new + 3
print(y)

tensor([[4., 5.],
        [6., 7.]], grad_fn=<AddBackward0>)


#### Second Layer

In [13]:
z = 3*y
print(z)

tensor([[12., 15.],
        [18., 21.]], grad_fn=<MulBackward0>)


#### Output Layer

In [14]:
out = z.mean() #calculates the average of z
print(out) 

tensor(16.5000, grad_fn=<MeanBackward0>)


#### Backward Propagation

In [15]:
out.backward() # runs backpropagation

In [17]:
x_new.grad #the derivative of y where x

tensor([[0.7500, 0.7500],
        [0.7500, 0.7500]])