In [1]:
import torch
import numpy as np

In [2]:
# check version
torch.__version__

'2.1.0'

#### Changing Numpy arrays to PyTorch tensors

In [3]:
arr = np.array([2,4,6,8,10])

In [6]:
#check type
type(arr)

numpy.ndarray

In [8]:
# another way to check the type
arr.dtype

dtype('int32')

In [9]:
# To change to a tensor
tens1 = torch.from_numpy(arr)

In [29]:
# To change to a tensor
tens2 = torch.as_tensor(arr)

In [11]:
# to change the first item in arr
arr[0] = 22

In [12]:
print(arr)
print(tens1)
print(tens2)

[22  4  6  8 10]
tensor([22,  4,  6,  8, 10], dtype=torch.int32)
tensor([22,  4,  6,  8, 10], dtype=torch.int32)


##### Note: Both tens1 and tens2 have a link to the arr because they share the same memory and to avoid this.

In [13]:
my_arr = np.array([2,4,6,8,10])

In [14]:
my_tensor = torch.tensor(my_arr) # doesn't have a link to my_arr
my_other_tensor = torch.from_numpy(my_arr) #has got a link to my_arr

In [16]:
my_arr[0] = 22

In [17]:
print(my_arr)
print(my_other_tensor)
print(my_tensor)

[22  4  6  8 10]
tensor([22,  4,  6,  8, 10], dtype=torch.int32)
tensor([ 2,  4,  6,  8, 10], dtype=torch.int32)


###### To make a 2-D tensor

In [18]:
arr2 = [[2,4,6],[3,7,9]]

In [19]:
my_tensor2 = torch.Tensor(arr2) #makes a tensor with floats(decimal numbers)

In [20]:
my_tensor2

tensor([[2., 4., 6.],
        [3., 7., 9.]])

In [22]:
#the third way to check type
my_tensor2.type()

'torch.FloatTensor'

In [26]:
#To change the type to integers
my_tensor3 = my_tensor2.type(torch.int64)

In [27]:
my_tensor3

tensor([[2, 4, 6],
        [3, 7, 9]])

In [28]:
my_tensor3.type()

'torch.LongTensor'